# Generated by Django 5.0 on 2025-09-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_song_album_song_deezer_id_song_preview_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
